"""Create departure hour and quarter dynamically

Revision ID: 957fdcd59895
Revises: eff8e241ff35
Create Date: 2018-02-03 18:08:33.114422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957fdcd59895'
down_revision = 'eff8e241ff35'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('journey') as batch_op:
        batch_op.drop_column('departure_quarter')
        batch_op.drop_column('departure_hour')
    # op.drop_column('journey', 'departure_quarter')
    # op.drop_column('journey', 'departure_hour')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey', sa.Column('departure_hour', sa.INTEGER(), nullable=False))
    op.add_column('journey', sa.Column('departure_quarter', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
